[toolchain]
channel = "nightly"
components = ["rust-src", "llvm-tools-preview"]
targets = ["x86_64-unknown-none"]

[dependencies]
core = { package = "libs-core", path = "../libs/core" } # 添加对 core 的依赖
alloc = { version = "0.1", optional = true } # 如果需要分配器支持
x86_64 = { version = "0.15.2", features = ["instructions", "abi_x86_interrupt"] }
spin = "0.10.0"
acpi = { version = "4.2.0", optional = true }